DROP TABLE IF EXISTS BCO;

CREATE TABLE BCO (dma_code INT, site_id INT) PARTITIONED by (dt INT, offer INT) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';
ALTER TABLE BCO ADD PARTITION(dt='20120426', offer='4159');

LOAD DATA LOCAL INPATH 'bco.txt' INTO TABLE BCO PARTITION (dt='20120426', offer='4159');
